### ISSUE TITLE
May I request that you include a PDF in the repository

### ISSUE THREAD

**Issue by mrose17** [UkoeHB/Mechanics-of-MobileCoin#1]
Hello! The last time I used LaTeX was in 1984 on my dissertation... For those of us who are a bit impaired, could you put up a PDF file in the repository? Thank you!

**Comment by UkoeHB** [comment]
Hi Marshall,

There already is a PDF in the repository, although the `.pdf` extension isn't visible because the name is too long. I will be updating with one new chapter per week until it is published.

Btw if you want to get back into LaTeX I highly recommend [Overleaf](https://www.overleaf.com/). For example this project can be compiled by: making an overleaf account -> uploading the project folder (git cloned) -> done (auto compiles server-side and displayed in-browser).

**Comment by mrose17** [comment]
Oops! I missed it. My apologies. thanks very much!
